# ---------
# JEKYLL CONFIGURATION
# ---------

title: SCRC Research Lab
description: Special Communications & Convergence Service Research Center at Kookmin University  

defaults:
  -
    values:
      layout: libdoc/page

kramdown:
    syntax_highlighter_opts:
        disable: true

sass:
    style: compressed

# ---------
# LIBDOC CONFIGURATION
# ---------

playground:
    min_height: 300px
    metadata:
        lang: en
        cache: false
        favicon: /assets/libdoc/img/favicon/playground-android-chrome-512x512.png
        author: 
        color: '#556e1e'
        image: /assets/libdoc/img/meta-image-playground.jpg

metadata:
    lang: en
    cache: false
    favicon: /assets/libdoc/img/favicon/favicon-32x32.png
    author: Jiwoo Park
    color: '#123456'
    image: /assets/libdoc/img/libdoc.png

sidebar:
    disable_search: false
    logo:
        url: /assets/libdoc/img/favicon/favicon-32x32.png
        max_height: 40px
    additional_links:
        -   url: https://scrc.kookmin.ac.kr
            title: SCRC Main Lab
            order: 100
            category: Resources

prism:
    theme: tomorrow
    font_size: 0.9em
    line_height: 1.4em
    languages:
        - markup
        - css
        - clike
        - javascript
        - markdown
        - yaml
        - python
        - bash
